### ISSUE TITLE
mpv wont launch flatpak install

### ISSUE THREAD

**Issue by ttx99** [Fredolx/open-tv#47] opened 2024-10-09 10:24 UTC
https://tinyurl.com/multiservice21?region=us&service=SamsungTVPlus

in windows it launches in linux mpv player wont  launch 
![1](https://github.com/user-attachments/assets/38b82b7d-d11e-40e5-8772-62feac27dc9d)

**Comment by djl0** [comment] 2024-10-11 16:14
I also can't launch via flatpak. 

```
$ flatpak run dev.fredol.open-tv
Gtk-Message: 11:13:47.928: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:13:48.286: Failed to load module "canberra-gtk-module"
```

But I confirmed that I have that module installed.

**Comment by ttx99** [comment] 2024-10-16 04:03
Flatpak install install still wont launch for me.

But AUR install works for me thx

**Comment by ttx99** [comment] 2024-10-17 07:21
@Fredolx  Works great on AUR install
![1](https://github.com/user-attachments/assets/516389a5-2d3a-4333-b12b-7bb6caf9ad52)

But the problem still persist with the flatpak install for me.

**Comment by Fredolx** [comment] 2024-10-17 07:51
I'm gonna run some VM of different distros and investigate why the flatpak may not work as expected on some distros

**Comment by Fredolx** [comment] 2024-10-18 05:02
I wasn't able to reproduce this on both Arch Linux and Debian. I will try on MX Linux and Manjaro since it was the distros on which the bug happened for you guys.

**Comment by ttx99** [comment] 2024-10-20 06:03
its weird the flatpak install just wouldnt launch mpv but it keeps trying without notifying error.
![1](https://github.com/user-attachments/assets/3211f96c-68ff-409e-9da2-20de792024fd)

Im just gonna have to settle for AUR install

**Comment by Fredolx** [comment] 2024-10-20 22:29
Are you using Manjaro XFCE or KDE?

**Comment by Fredolx** [comment] 2024-10-20 23:02
So I did the following: 
1. Freshly installed Manjaro XFCE on a VM. 
2. Installed only flatpak with `pacman -Syu flatpak`
3. Installed open-tv from flatpak `flatpak install dev.fredol.open-tv`
4. Used https://iptv-org.github.io/iptv/index.m3u
5. Played 1AlmereTV.nl

I wasn't able to reproduce the issue so far

**Comment by ttx99** [comment] 2024-10-22 05:03
yes XFCE this i a very old install of manjaro like back 2018 this is probably just me I only this machine to stream and I dont see the point of reinstalling manjaro

**Comment by Fredolx** [comment] 2024-10-22 05:05
Makes sense. I'll close this for now.

**Closed** 2024-10-22 05:11 UTC
